[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = ".next"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/manifest.json"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/firebase-messaging-sw.js"
[headers.values]
Service-Worker-Allowed = "/"
Cache-Control = "no-cache"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "netlify/functions"

[dev]
framework = "#static"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"
NEXT_PUBLIC_FIREBASE_API_KEY = "${NEXT_PUBLIC_FIREBASE_API_KEY}"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "${NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
NEXT_PUBLIC_FIREBASE_APP_ID = "${NEXT_PUBLIC_FIREBASE_APP_ID}"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}"
NEXT_PUBLIC_FIREBASE_VAPID_KEY = "${NEXT_PUBLIC_FIREBASE_VAPID_KEY}"